#!/bin/sh

DIR="/keychain.io"

cat <<-EOF > ${DIR}/.env
AWS_ACCESS_KEY_ID=${YOUR_AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${YOUR_AWS_SECRET_ACCESS_KEY}
SENDGRID_USERNAME=${YOUR_SENDGRID_USERNAME}
SENDGRID_PASSWORD=${YOUR_SENDGRID_PASSWORD}
KEYCHAIN_BUCKET_NAME=${YOUR_KEYCHAIN_BUCKET_NAME}
EOF

/usr/local/bin/foreman start -d ${DIR}
